# Generated by Django 6.1.2 on 2026-10-07 16:42

import apps.utils.validacoes
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nro_associado', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='número de associado')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('cargo', models.CharField(choices=[('admin', 'Administrador'), ('franqueado', 'Franqueado')], default='franqueado', max_length=20, verbose_name='cargo')),
                ('whatsapp', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+\\d{2}\\d{2}9\\d{8}$', message='Numero de telefone invalido')], verbose_name='WhatsApp')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[apps.utils.validacoes.validar_cpf], verbose_name='CPF')),
                ('tipo_comunicacao', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('whatsapp_email', 'WhatsApp e Email')], default='whatsapp_email', max_length=20, verbose_name='tipo de comunicação')),
                ('status', models.CharField(choices=[('aguardando_validacao', 'Aguardando Validação'), ('validacao_recusada', 'Validação Recusada'), ('ativo', 'Ativo'), ('inativo', 'Inativo'), ('bloqueado', 'Bloqueado')], default='aguardando_validacao', max_length=20, verbose_name='status')),
                ('data_admissao', models.DateField(blank=True, null=True, verbose_name='data de admissão')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AprovacaoCadastro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_aprovacao', models.DateTimeField(auto_now_add=True, verbose_name='data da avaliação')),
                ('motivo_recusa', models.TextField(blank=True, null=True, verbose_name='motivo da recusa')),
                ('aprovado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovacoes_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='avaliado por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprovacoes', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'aprovação de cadastro',
                'verbose_name_plural': 'aprovações de cadastro',
                'ordering': ['-data_aprovacao'],
            },
        ),
        migrations.CreateModel(
            name='MotivoDesativacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=100, verbose_name='motivo')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motivos_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motivos_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'motivo de desativação',
                'verbose_name_plural': 'motivos de desativação',
                'ordering': ['motivo'],
            },
        ),
    ]
