# Generated by Django 6.1.2 on 2026-10-07 16:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='membros/')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem de exibição')),
            ],
            options={
                'verbose_name': 'Membro AFSB',
                'verbose_name_plural': 'Membros AFSB',
                'ordering': ('ordem', 'nome'),
            },
        ),
    ]
