# Generated by Django 6.1.2 on 2026-10-07 16:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=100, verbose_name='título')),
                ('subtitulo', models.CharField(max_length=200, verbose_name='subtítulo')),
                ('texto', models.TextField(verbose_name='texto')),
                ('imagem', models.ImageField(upload_to='noticias/', verbose_name='imagem')),
            ],
            options={
                'verbose_name': 'notícia',
                'verbose_name_plural': 'notícias',
                'ordering': ('-criado_em',),
            },
        ),
    ]
