# Generated by Django 6.1.2 on 2026-10-07 16:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franquia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nro_da_loja', models.PositiveIntegerField(unique=True, verbose_name='número da loja')),
                ('nome_fantasia', models.CharField(max_length=100, verbose_name='nome fantasia')),
                ('razao_social', models.CharField(max_length=100, verbose_name='razão social')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('estado', models.CharField(max_length=2, verbose_name='estado')),
                ('cidade', models.CharField(max_length=100, verbose_name='cidade')),
                ('bairro', models.CharField(max_length=100, verbose_name='bairro')),
                ('rua', models.CharField(max_length=100, verbose_name='rua')),
                ('numero', models.CharField(max_length=10, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='complemento')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'franquia',
                'verbose_name_plural': 'franquias',
                'ordering': ('nro_da_loja',),
            },
        ),
    ]
