"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _carregar_env(caminho):
    """
    Lê o .env da raiz do repositório (CHAVE=valor, aspas opcionais) sem
    sobrescrever o que já vem do ambiente. No compose ele chega por env_file;
    fora dele (venv local), por aqui. Aspas simples evitam que o '$' da chave
    do Asaas seja interpretado pelo shell/compose.
    """
    if not caminho.exists():
        return
    for linha in caminho.read_text(encoding='utf-8').splitlines():
        linha = linha.strip()
        if not linha or linha.startswith('#') or '=' not in linha:
            continue
        chave, valor = (parte.strip() for parte in linha.split('=', 1))
        if len(valor) >= 2 and valor[0] == valor[-1] and valor[0] in ('"', "'"):
            valor = valor[1:-1]
        os.environ.setdefault(chave, valor)


_carregar_env(BASE_DIR.parent / '.env')


def _env_bool(nome, padrao='0'):
    return os.environ.get(nome, padrao).strip().lower() in ('1', 'true', 'sim', 'yes')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', '0')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    raise ImproperlyConfigured('Defina DJANGO_SECRET_KEY no .env da raiz (ver .env.example).')

# Vazio + DEBUG libera localhost; no compose o nginx chega como "backend".
ALLOWED_HOSTS = [h for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h]

# Atrás do Caddy (HTTPS): origens aceitas no CSRF (admin/sessão) e esquema real.
CSRF_TRUSTED_ORIGINS = [o for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o]
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

DEFAULT_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    "rest_framework",
    "rest_framework.authtoken",
]

OUR_APPS = [
    'apps.auditoria',
    'apps.cobranca',
    'apps.documento',
    'apps.evento',
    'apps.franquia',
    'apps.membro',
    'apps.noticia',
    'apps.parceiro',
    'apps.usuario',
]

INSTALLED_APPS = DEFAULT_APPS + THIRD_PARTY_APPS + OUR_APPS

AUTH_USER_MODEL = 'usuario.Usuario'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# Sem EMAIL_HOST o e-mail só aparece no console (dev). Com host, sai por SMTP.
_EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
        'OPTIONS': {
            'host': _EMAIL_HOST,
            'port': int(os.environ.get('EMAIL_PORT', '587')),
            'username': os.environ.get('EMAIL_HOST_USER', ''),
            'password': os.environ.get('EMAIL_HOST_PASSWORD', ''),
            'use_tls': _env_bool('EMAIL_USE_TLS', '1'),
        },
    } if _EMAIL_HOST else {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# Storages
# https://django-storages.readthedocs.io/en/latest/backends/s3_compatible/backblaze-B2.html

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
            "bucket_name": os.environ.get("B2_BUCKET_NAME", ""),
            "region_name": os.environ.get("B2_REGION", ""),
            "endpoint_url": os.environ.get("B2_ENDPOINT_URL", ""),
            "access_key": os.environ.get("B2_ACCESS_KEY", ""),
            "secret_key": os.environ.get("B2_SECRET_KEY", ""),
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# API
# Token no header (painel/SPA) e sessão (Django admin / API navegável).
# Padrão fechado: só staff. Endpoint público ou de associado declara a própria permissão.

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAdminUser',),
    # Rotas públicas que criam/validam acesso: limita tentativas por IP.
    'DEFAULT_THROTTLE_RATES': {'cadastro': '10/hour', 'login': '30/hour'},
}


# Asaas
# Sem chave, nada é enviado ao Asaas: reemissão e baixa avisam que falta configurar.

ASAAS_API_KEY = os.environ.get('ASAAS_API_KEY', '')
ASAAS_BASE_URL = os.environ.get('ASAAS_BASE_URL', 'https://api-sandbox.asaas.com/v3')
# Trava geral: nada é emitido no Asaas (geração mensal, reemissão, "pagar") até a
# AFSB comunicar os associados sobre a troca de sistema. Liberar com "1".
COBRANCA_EMISSAO_LIBERADA = _env_bool('COBRANCA_EMISSAO_LIBERADA', '0')
# Token que o Asaas envia no header asaas-access-token dos webhooks.
ASAAS_WEBHOOK_TOKEN = os.environ.get('ASAAS_WEBHOOK_TOKEN', '')
DEFAULT_FROM_EMAIL = os.environ.get('DJANGO_DEFAULT_FROM_EMAIL', 'AFSB <nao-responda@afsb.com.br>')
