# Generated by Django 6.1.2 on 2026-10-07 16:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=100, verbose_name='título')),
                ('arquivo', models.FileField(upload_to='documentos/', verbose_name='arquivo')),
                ('tipo', models.CharField(choices=[('documento', 'Documento'), ('palestra', 'Palestra'), ('ata_de_reuniao', 'Ata de Reunião')], max_length=30, verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ('-criado_em',),
            },
        ),
    ]
