# Generated by Django 6.1.2 on 2026-10-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('documento', 'Documento'), ('palestra', 'Palestra'), ('ata_de_reuniao', 'Ata de Reunião'), ('video', 'Vídeo')], max_length=30, verbose_name='tipo'),
        ),
    ]
