# Generated by Django 6.1.2 on 2026-10-07 16:42

import apps.cobranca.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periodicidade', models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual')], max_length=10, verbose_name='periodicidade')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='ano')),
                ('mes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='mês')),
                ('valor_cheio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor cheio')),
                ('valor_desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor com desconto')),
                ('valor_personalizado', models.BooleanField(default=False, verbose_name='valor personalizado')),
                ('data_vencimento', models.DateField(verbose_name='data de vencimento')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('parcial', 'Parcialmente Paga'), ('paga', 'Paga'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='aberta', max_length=10, verbose_name='status')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor pago')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='data de pagamento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
            ],
            options={
                'verbose_name': 'competência',
                'verbose_name_plural': 'competências',
                'ordering': ('ano', 'mes'),
            },
        ),
        migrations.CreateModel(
            name='PerfilCobranca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ')], max_length=4, verbose_name='tipo de documento')),
                ('documento', models.CharField(max_length=18, verbose_name='CPF/CNPJ')),
                ('nome_pagador', models.CharField(max_length=100, verbose_name='nome do pagador')),
                ('forma_pagamento', models.CharField(choices=[('cartao_recorrente', 'Cartão Recorrente'), ('cartao_parcelado', 'Cartão Parcelado'), ('pix_boleto', 'PIX e Boleto')], max_length=20, verbose_name='forma de pagamento')),
                ('dia_vencimento', models.PositiveSmallIntegerField(choices=[(15, 'Dia 15'), (25, 'Dia 25')], verbose_name='dia de vencimento')),
                ('qtd_lojas', models.PositiveSmallIntegerField(verbose_name='quantidade de lojas')),
                ('valor_personalizado_cheio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor personalizado cheio')),
                ('valor_personalizado_desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor personalizado com desconto')),
                ('valor_personalizado_inicio', models.DateField(blank=True, null=True, verbose_name='início do valor personalizado')),
                ('valor_personalizado_fim', models.DateField(blank=True, null=True, verbose_name='fim do valor personalizado')),
                ('motivo_valor_personalizado', models.TextField(blank=True, null=True, verbose_name='motivo do valor personalizado')),
                ('qtd_parcelas', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='quantidade de parcelas')),
                ('asaas_customer_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='ID do cliente no Asaas')),
                ('asaas_subscription_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID da assinatura no Asaas')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='observação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
            ],
            options={
                'verbose_name': 'perfil de cobrança',
                'verbose_name_plural': 'perfis de cobrança',
                'ordering': ('nome_pagador', 'documento'),
            },
        ),
        migrations.CreateModel(
            name='RecebimentoExterno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('forma_pagamento', models.CharField(choices=[('pix_direto', 'PIX Direto'), ('transferencia', 'Transferência Bancária'), ('dinheiro', 'Dinheiro'), ('outro', 'Outro')], default='pix_direto', max_length=20, verbose_name='forma de pagamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('data_pagamento', models.DateField(verbose_name='data de pagamento')),
                ('comprovante', models.FileField(upload_to=apps.cobranca.models.caminho_comprovante, verbose_name='comprovante')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='observação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
            ],
            options={
                'verbose_name': 'recebimento externo',
                'verbose_name_plural': 'recebimentos externos',
            },
        ),
        migrations.CreateModel(
            name='TabelaValor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modalidade', models.CharField(choices=[('mensal', 'Boleto/PIX - Mensal'), ('anual', 'Cartão de Crédito - Anual')], max_length=10, verbose_name='modalidade')),
                ('qtd_lojas', models.PositiveSmallIntegerField(verbose_name='quantidade de lojas')),
                ('valor_cheio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor cheio')),
                ('valor_desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor com desconto')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
            ],
            options={
                'verbose_name': 'tabela de valor',
                'verbose_name_plural': 'tabela de valores',
                'ordering': ('modalidade', 'qtd_lojas'),
            },
        ),
        migrations.CreateModel(
            name='WebhookAsaas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asaas_event_id', models.CharField(max_length=100, unique=True, verbose_name='ID do evento no Asaas')),
                ('evento', models.CharField(max_length=50, verbose_name='evento')),
                ('payload', models.JSONField(verbose_name='conteúdo')),
                ('processado', models.BooleanField(default=False, verbose_name='processado')),
                ('erro', models.TextField(blank=True, null=True, verbose_name='erro')),
                ('data_recebimento', models.DateTimeField(auto_now_add=True, verbose_name='data de recebimento')),
            ],
            options={
                'verbose_name': 'webhook do Asaas',
                'verbose_name_plural': 'webhooks do Asaas',
                'ordering': ('-data_recebimento',),
            },
        ),
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asaas_payment_id', models.CharField(max_length=50, unique=True, verbose_name='ID da cobrança no Asaas')),
                ('asaas_installment_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='ID do parcelamento no Asaas')),
                ('asaas_subscription_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='ID da assinatura no Asaas')),
                ('tipo_cobranca', models.CharField(choices=[('BOLETO', 'Boleto'), ('PIX', 'PIX'), ('CREDIT_CARD', 'Cartão de Crédito'), ('UNDEFINED', 'Pergunte ao Cliente')], max_length=20, verbose_name='tipo de cobrança')),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando Pagamento'), ('AWAITING_RISK_ANALYSIS', 'Em Análise de Risco'), ('CONFIRMED', 'Confirmada'), ('RECEIVED', 'Recebida'), ('RECEIVED_IN_CASH', 'Recebida em Dinheiro'), ('OVERDUE', 'Vencida'), ('REFUND_REQUESTED', 'Estorno Solicitado'), ('REFUNDED', 'Estornada'), ('CHARGEBACK_REQUESTED', 'Chargeback Solicitado'), ('CHARGEBACK_DISPUTE', 'Em Disputa de Chargeback'), ('AWAITING_CHARGEBACK_REVERSAL', 'Aguardando Reversão de Chargeback'), ('DUNNING_REQUESTED', 'Negativação Solicitada'), ('DUNNING_RECEIVED', 'Negativação Recebida'), ('DELETED', 'Removida')], default='PENDING', max_length=30, verbose_name='status')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('valor_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor líquido')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor pago')),
                ('data_vencimento', models.DateField(verbose_name='data de vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='data de pagamento')),
                ('nro_parcela', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='número da parcela')),
                ('descricao', models.CharField(blank=True, max_length=500, null=True, verbose_name='descrição')),
                ('invoice_url', models.URLField(blank=True, null=True, verbose_name='link da fatura')),
                ('boleto_url', models.URLField(blank=True, null=True, verbose_name='link do boleto')),
                ('pix_copia_cola', models.TextField(blank=True, null=True, verbose_name='PIX copia e cola')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='retorno do Asaas')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas', to='cobranca.competencia', verbose_name='competência')),
            ],
            options={
                'verbose_name': 'cobrança',
                'verbose_name_plural': 'cobranças',
                'ordering': ('data_vencimento', 'nro_parcela'),
            },
        ),
    ]
