# Generated by Django 6.1.2 on 2026-10-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cobranca', '0001_initial'),
        ('franquia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcobranca',
            name='franquias',
            field=models.ManyToManyField(blank=True, related_name='perfis_cobranca', to='franquia.franquia', verbose_name='lojas'),
        ),
    ]
