# Generated by Django 6.1.2 on 2026-10-07 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cobranca', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcobranca',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfis_cobranca', to=settings.AUTH_USER_MODEL, verbose_name='associado'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competencias', to='cobranca.perfilcobranca', verbose_name='perfil de cobrança'),
        ),
        migrations.AddField(
            model_name='recebimentoexterno',
            name='cobranca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recebimentos_externos', to='cobranca.cobranca', verbose_name='cobrança baixada'),
        ),
        migrations.AddField(
            model_name='recebimentoexterno',
            name='competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_externos', to='cobranca.competencia', verbose_name='competência'),
        ),
        migrations.AddField(
            model_name='recebimentoexterno',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_externos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='registrado por'),
        ),
        migrations.AddConstraint(
            model_name='tabelavalor',
            constraint=models.UniqueConstraint(fields=('modalidade', 'qtd_lojas'), name='tabela_valor_unica_por_lojas'),
        ),
        migrations.AddField(
            model_name='webhookasaas',
            name='cobranca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to='cobranca.cobranca', verbose_name='cobrança'),
        ),
        migrations.AddConstraint(
            model_name='perfilcobranca',
            constraint=models.CheckConstraint(condition=models.Q(('valor_personalizado_cheio__isnull', True), models.Q(('motivo_valor_personalizado__isnull', False), ('valor_personalizado_inicio__isnull', False)), _connector='OR'), name='perfil_valor_personalizado_com_inicio_e_motivo'),
        ),
        migrations.AddConstraint(
            model_name='competencia',
            constraint=models.UniqueConstraint(fields=('perfil', 'ano', 'mes'), name='competencia_unica_por_periodo'),
        ),
        migrations.AddConstraint(
            model_name='competencia',
            constraint=models.UniqueConstraint(condition=models.Q(('mes__isnull', True)), fields=('perfil', 'ano'), name='competencia_anual_unica'),
        ),
        migrations.AddConstraint(
            model_name='competencia',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mes__gte', 1), ('mes__lte', 12), ('periodicidade', 'mensal')), models.Q(('mes__isnull', True), ('periodicidade', 'anual')), _connector='OR'), name='competencia_mes_coerente_com_periodicidade'),
        ),
        migrations.AddConstraint(
            model_name='recebimentoexterno',
            constraint=models.CheckConstraint(condition=models.Q(('comprovante', ''), _negated=True), name='recebimento_externo_com_comprovante'),
        ),
        migrations.AddConstraint(
            model_name='recebimentoexterno',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='recebimento_externo_valor_positivo'),
        ),
    ]
